NumPy, short for Numerical Python, is the fundamental package required for high performance scientific computing and data analysis. 

Numpy main ubject: multi-dimensional array
In numpy dimentions are called axes , the number of axes are rank.


NumPy’s array class is called <span style="color:green"> ndarray</span>. It is also known by the alias array.
In Numpy we use this for importing (this is better):
<span style="color:green"> Import Numpy as np </span>
   
Ndarray : n-dimensional array

Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements.

Whenever you see “array”, “NumPy array”, or “ndarray” in the text, they all refer to:the ndarray object.


The easiest way to create an array is to use the array function :

In [1]:
import numpy as np

at first we make a list

In [24]:
d = ["s","d"]
d

['s', 'd']

with the following code , we'll make it as an array

In [26]:
arr0=np.array(d)

In [31]:
arr0

array(['s', 'd'], dtype='<U1')

In [32]:
d2 = [[5,1,0,6],[4,3,10,7]]

In [33]:
arr = np.array(d2)
arr

array([[ 5,  1,  0,  6],
       [ 4,  3, 10,  7]])

We can perform math operations on the arrays

In [14]:
d2*3

[[5, 1, 0, 6],
 [4, 3, 10, 7],
 [5, 1, 0, 6],
 [4, 3, 10, 7],
 [5, 1, 0, 6],
 [4, 3, 10, 7]]

In [7]:
arr * 3

array([[15,  3,  0, 18],
       [12,  9, 30, 21]])

In [8]:
arr + 3

array([[ 8,  4,  3,  9],
       [ 7,  6, 13, 10]])

In [9]:
arr - 3

array([[ 2, -2, -3,  3],
       [ 1,  0,  7,  4]])

In [10]:
arr / 3

array([[1.66666667, 0.33333333, 0.        , 2.        ],
       [1.33333333, 1.        , 3.33333333, 2.33333333]])

In [11]:
arr // 3

array([[1, 0, 0, 2],
       [1, 1, 3, 2]], dtype=int32)

it shows the array's dimensional

In [12]:
arr.ndim

2

it shows rows and columns of array. the first number is the row's number

In [13]:
arr.shape

(2, 4)

shows the size of array

In [14]:
arr.size

8

shows the type of elemnts

In [15]:
arr.dtype

dtype('int32')

in np.array , there are another functions for making array

In [15]:
c = np.ones(4)

In [17]:
c.shape

(4,)

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [20]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

#### <span style = "color:red">Operations between Arrays and Scalars

Arrays are important because they enable you to express batch operations on data without writing any for loops. that called vectorization.

In [21]:
arr *arr

array([[ 25,   1,   0,  36],
       [ 16,   9, 100,  49]])

In [22]:
arr - arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
arr + arr

array([[10,  2,  0, 12],
       [ 8,  6, 20, 14]])

In [24]:
arr ** arr

array([[      3125,          1,          1,      46656],
       [       256,         27, 1410065408,     823543]], dtype=int32)

In [25]:
1 / arr

C:\Users\Yas\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.2       , 1.        ,        inf, 0.16666667],
       [0.25      , 0.33333333, 0.1       , 0.14285714]])

#### <span style="color:red">Basic Indexing and Slicing 

work with One-dimensional arrays are simple; on the surface they act similarly to Python lists: 

In [26]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [27]:
a[2:6]

array([2, 3, 4, 5])

In [28]:
a[2:6] = 9
a

array([0, 1, 9, 9, 9, 9])

In [29]:
a[3] = 4
a

array([0, 1, 9, 4, 9, 9])

 An important first distinction from lists is that array slices are views on the original array. This means that the data is not copied, and any modifications to the view will be reflected in the source array:

In [30]:
a_slices = a[:4]
a_slices

array([0, 1, 9, 4])

In [31]:
a_slices[1] = 134

In [32]:
a

array([  0, 134,   9,   4,   9,   9])

In [33]:
a_slices[:] = 345

In [34]:
a

array([345, 345, 345, 345,   9,   9])

if we want a copy of our indexing instead of show

In [35]:
b = np.ones(7)
b

array([1., 1., 1., 1., 1., 1., 1.])

In [36]:
b_slices = b[:5].copy()

In [37]:
b_slices[4] = 125
b

array([1., 1., 1., 1., 1., 1., 1.])

<span style="color:green">
2-dimensional 

With higher dimensional arrays, you have many more options. In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays:

In [34]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr2d.ndim

2

In [40]:
arr2d[2]

array([7, 8, 9])

In [36]:
 arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [37]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
arr3d.ndim

3

In [39]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr3dd = arr3d[0].copy()
arr3dd[0]

array([1, 2, 3])

In [41]:
arr3dd[0] = 24
arr3dd

array([[24, 24, 24],
       [ 4,  5,  6]])

In [42]:
arr3d[1,0]

array([7, 8, 9])

<span style="color:red">
indexing with slices

In [44]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [51]:
arr2d[2,1] 

8

In [85]:
 arr2d[:,1:2] 

array([[2],
       [5],
       [8]])

In [43]:
 arr2d[:, 2:3] 

array([[3],
       [6],
       [9]])

In [87]:
arr2d[:, 1]

array([2, 5, 8])

<span style="color:red">
Boolean Indexing 

 we have a example of some data in an array of names with duplicates.
 

In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [48]:
data = np.random.randn(7, 4)

In [49]:
data

array([[-0.40510903,  0.70949872,  0.27336079,  0.036201  ],
       [ 1.04426242, -0.45397825, -0.87631521,  1.0781549 ],
       [-0.11956663,  1.36105613,  0.27350452, -0.33929882],
       [ 2.28767161, -2.10740508,  0.26705772,  0.27845062],
       [ 0.60716097, -0.97638142,  0.79565302, -1.72727778],
       [-0.19565646,  2.64916759,  0.3225256 ,  0.00313695],
       [-0.32122176, -0.48961015, -0.52795371,  0.33596027]])

In [108]:
names == 'Joe' 

array([False,  True, False, False, False,  True,  True])

In [56]:
names2 = np.array([False,False,True,True])
data[:,names2]

array([[ 0.27336079,  0.036201  ],
       [-0.87631521,  1.0781549 ],
       [ 0.27350452, -0.33929882],
       [ 0.26705772,  0.27845062],
       [ 0.79565302, -1.72727778],
       [ 0.3225256 ,  0.00313695],
       [-0.52795371,  0.33596027]])

In [58]:
data[names == 'Joe']

array([[ 1.04426242, -0.45397825, -0.87631521,  1.0781549 ],
       [-0.19565646,  2.64916759,  0.3225256 ,  0.00313695],
       [-0.32122176, -0.48961015, -0.52795371,  0.33596027]])

In [110]:
data[names == 'Joe', 2:] 

array([[ 0.02897986, -1.20684934],
       [-1.30109087, -1.41723854],
       [ 2.28946693,  0.16694765]])

In [129]:
gigi = (names == 'Bob') | (names == 'Will')

In [130]:
gigi

array([ True, False,  True,  True,  True, False, False])

In [131]:
data[gigi]

array([[ 1.14838968,  0.3375462 , -0.81168311,  0.50738445],
       [-1.12005906,  0.71170394,  0.87333665, -0.23059008],
       [ 0.85129102, -0.44704241, -0.41744549,  0.14826399],
       [ 0.63723647,  1.26748696, -1.61244225, -1.460001  ]])

for deleting the negative values

In [135]:
data[data < 0] = 0
data

array([[1.14838968, 0.3375462 , 0.        , 0.50738445],
       [1.13441425, 0.        , 0.02897986, 0.        ],
       [0.        , 0.71170394, 0.87333665, 0.        ],
       [0.85129102, 0.        , 0.        , 0.14826399],
       [0.63723647, 1.26748696, 0.        , 0.        ],
       [1.5576355 , 0.        , 0.        , 0.        ],
       [0.        , 0.31583766, 2.28946693, 0.16694765]])

In [139]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.13441425, 0.        , 0.02897986, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.5576355 , 0.        , 0.        , 0.        ],
       [0.        , 0.31583766, 2.28946693, 0.16694765]])

<span style="color:red">
Fancy Indexing 

Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays. 

In [61]:
arr4 = np.empty((8,4))
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
for i in range(8): 
     arr4[i] = i

In [63]:
arr4

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [64]:
arr4[[7,6,5,1,0,2,6,2]]

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [5., 5., 5., 5.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [2., 2., 2., 2.],
       [6., 6., 6., 6.],
       [2., 2., 2., 2.]])

In [65]:
arr4

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [155]:
arr4[[-2,-3,-6]]

array([[6., 6., 6., 6.],
       [5., 5., 5., 5.],
       [2., 2., 2., 2.]])

In [66]:
arr5 = np.arange(60).reshape(10,6)

In [67]:
arr5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [162]:
arr5[[1,2,3,7] , [1,5,3,2]]

array([ 7, 17, 21, 44])

<span style="color:crimson">Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array.</span>