### <span style="color:red"> File Input and Output with Arrays </span> 
NumPy is able to save and load data from disk either in text or binary format.

In [1]:
import numpy as np

##### <span style="color:red"> Storing Arrays on Disk in Binary Format </span>

<span style="color:darkorange">np.save</span> and <span style="color:darkorange">np.load</span> are the two workhorse functions for efficiently saving and loading array data on disk. they are saved by default with .npy format

In [2]:
arr = np.arange(9).reshape(3,3)
arr2 = np.arange(6)
arr3 = np.arange(4).reshape(2,2)

In [3]:
np.save('some_array', arr)

In [4]:
np.load('some_array.npy') 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.savez('array_archive.npz', a=arr, b=arr2 , c=arr3) 

In [6]:
arch = np.load('array_archive.npz')

In [7]:
arch['a']

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### <span style="color:red">Saving and Loading Text Files </span>

In [8]:
f = open('array_ex.txt' , 'w')
type(f)

_io.TextIOWrapper

In [9]:
f.write('0.580052,0.186730,1.040717,1.134411, 0.194163,-0.636917,-0.938659,0.124094 ,-0.126410,0.268607,-0.695724,0.047428 ,-1.484413,0.004176,-0.744203,0.005487, 2.302869,0.200131,1.670238,-1.881090 ,-0.193230,1.047233,0.482803,0.960334')
f.close()

In [10]:
np.loadtxt('array_ex.txt', dtype='float64' ,delimiter=',' )

array([ 0.580052,  0.18673 ,  1.040717,  1.134411,  0.194163, -0.636917,
       -0.938659,  0.124094, -0.12641 ,  0.268607, -0.695724,  0.047428,
       -1.484413,  0.004176, -0.744203,  0.005487,  2.302869,  0.200131,
        1.670238, -1.88109 , -0.19323 ,  1.047233,  0.482803,  0.960334])

##### <span style="color:red">Linear Algebra </span>

<span style="color:crimson">functions and their description </span>

<span style="color:purple">diag:</span> Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zeros on the off-diagonal 

<span style="color:purple">dot:</span>  Matrix multiplicatio

<span style="color:purple">trace:</span> Compute the sum of the diagonal elements 

<span style="color:purple">det:</span> Compute the matrix determinant 

<span style="color:purple">eig:</span> Compute the eigenvalues and eigenvectors of a square matrix 

<span style="color:purple">inv:</span> Compute the inverse of a square matrix

<span style="color:purple">pinv:</span> Compute the Moore-Penrose pseudo-inverse inverse of a square matrix 

<span style="color:purple">qr:</span> Compute the QR decomposition 

<span style="color:purple">svd:</span> Compute the singular value decomposition (SVD) 

<span style="color:purple">solve:</span> Solve the linear system Ax = b for x, where A is a square matrix 

<span style="color:purple">lstsq:</span> Compute the least-squares solution to y = Xb


In [11]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [12]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [13]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [14]:
x.dot(y)  # equivalently np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

numpy.linalg has a standard set of matrix decompositions and things like inverse and determinant.

In [15]:
from numpy.linalg import inv, qr

In [16]:
x = np.random.randn(3,3)

In [17]:
mat = x.T.dot(x)

In [18]:
mat

array([[ 2.2172624 , -0.25886371,  2.00779695],
       [-0.25886371,  4.57145357,  1.38645704],
       [ 2.00779695,  1.38645704,  3.47449362]])

In [19]:
inv(mat)

array([[ 1.28639396,  0.33936674, -0.87878569],
       [ 0.33936674,  0.3383966 , -0.33114231],
       [-0.87878569, -0.33114231,  0.92777198]])

In [20]:
r = qr(mat)

In [21]:
r

(array([[-0.73849234,  0.1071525 , -0.66569318],
        [ 0.08621842, -0.96418   , -0.25084521],
        [-0.66872674, -0.24264228,  0.70280102]]),
 array([[-3.00241762, -0.34184853, -3.68669131],
        [ 0.        , -4.77185508, -1.96471272],
        [ 0.        ,  0.        ,  0.75751482]]))

##### <span style="color:red"> Random Number Generation </span>

The <span style="color:darkorange">numpy.random </span>module supplements the built-in Python random with functions for efficiently generating whole arrays of sample values from many kinds of probability distributions.

<span style="color:crimson">Partial list of numpy.random functions </span>

<span style="color:darkviolet">seed:</span> Seed the random number generator 

<span style="color:darkviolet">permutation:</span> Return a random permutation of a sequence, or return a permuted range 

<span style="color:darkviolet">shuffle:</span> Randomly permute a sequence in place 

<span style="color:darkviolet">rand:</span> Draw samples from a uniform distribution 

<span style="color:darkviolet">randint:</span> Draw random integers from a given low-to-high range

<span style="color:darkviolet">randn:</span> Draw samples from a normal distribution with mean 0 and standard 

<span style="color:darkviolet">binomial:</span> Draw samples a binomial distribution

<span style="color:darkviolet">normal:</span> Draw samples from a normal (Gaussian) distribution 

<span style="color:darkviolet">beta:</span> Draw samples from a beta distribution 

<span style="color:darkviolet">chisquare:</span> Draw samples from a chi-square distribution 

<span style="color:darkviolet">gamma:</span> Draw samples from a gamma distribution 

<span style="color:darkviolet">uniform:</span> Draw samples from a uniform [0, 1) distribution

In [22]:
s = np.random.normal(size=(4, 4))
s

array([[ 0.22060875,  1.35112151, -2.07434395,  1.03304592],
       [ 1.20327905,  1.11836371,  0.42388545, -0.10101365],
       [-1.36758781,  0.04368045,  1.90333014, -0.31337932],
       [-1.9157095 , -0.57526992,  0.58308493, -1.17848322]])

In [23]:
from random import normalvariate

In [27]:
N = 1000000

In [31]:
samples = [normalvariate(0, 1) for _ in range(N)] #for large samples

In [32]:
ss = np.random.normal(size=N) 

##### <span style="color:red">Example: Random Walks </span>

An illustrative application of utilizing array operations is in the simulation of random walks. Let’s first consider a simple random walk starting at 0 with steps of 1 and -1 occurring with equal probability. A pure Python way to implement a single random walk with 1,000 steps using the built-in random module:

In [40]:
import random
position = 0
walk = [position] 
steps = 1000 
for i in range(steps):   
    step = 1 if random.randint(0, 1) else -1    
    position += step   
    walk.append(position) 

use the np.random module to draw 1,000 coin flips at once, set these to 1 and -1, and compute the cumulative sum: 

In [48]:
nsteps = 1000

In [55]:
draws = np.random.randint(0, 2, size=nsteps)

In [56]:
steps = np.where(draws > 0, 1, -1)

In [57]:
walk = steps.cumsum()

In [58]:
walk.min()

-17

In [59]:
walk.max()

19

In [60]:
(np.abs(walk) >= 10).argmax() 

23